### ISSUE TITLE
Could I use `Form Vue Component` on `Confirm`?

### ISSUE THREAD

**Issue by thearabbit** [sj82516/vue-alertify#10]
I would like to create `Dialog/Modal with Form Component`.
Could example?

![image](https://user-images.githubusercontent.com/4495160/47054058-17f7ed80-d1da-11e8-9ca6-ecbeeea7b561.png)

**Comment by sj82516** [comment]
I think this is not support by alertify.js
Maybe you need to build up by yourself. :/
