### ISSUE TITLE
Prompt with password type

### ISSUE THREAD

**Issue by angujo** [sj82516/vue-alertify#11]
Hi Good people,
A great tool it is. Was looking around on how to set the prompt as a password as documented in alertify https://alertifyjs.com/prompt/type.html 

Kindly advice if this is possible and how to go about it. Have tried;

`this.$alertify.promptWithTitle('Title','Msg','',()=>{},()=>{}).set('type','password');`

to no success

**Comment by sj82516** [comment]
Already fix now.  
You can use alertify.js chain method as you need. 
Feel free to open issue :)
