### ISSUE TITLE
How to access defaults

### ISSUE THREAD

**Issue by jersingh** [sj82516/vue-alertify#5]
How would one set up default position:

defaults.notifier.position = 'top-right';

In my main entry point I tried the following but to no avail:

```
import Vue from 'vue';
import VueAlertify from 'vue-alertify';
import App from './App';
import Router from './routes';

Vue.use(VueAlertify);

// alertify.defaults.notifier.position = 'top-right';
$alertify.defaults.notifier.position = 'top-right';
```

Thanks

**Comment by sj82516** [comment]
would try these two days.

**Comment by jersingh** [comment]
Any luck with this issue?

**Comment by sj82516** [comment]
It seems that I didn't export alertify so you cannot set the default values.
Would try to fix ASAP.  
Sorry for the delay
