### ISSUE TITLE
instructions don't match for many of the properties in $alertify

### ISSUE THREAD

**Issue by rowej83** [sj82516/vue-alertify#8]
For instance, 

Instructions for prompt with title states to use this.$alertify.prompt when really it needs to be this.$alertify.promptWithTitle

working example ( in TestComponent.vue)

<a href="https://codesandbox.io/s/oo23v06j35">
  <img alt="Edit Vuex exercise" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

**Comment by sj82516** [comment]
update readme
