### ISSUE TITLE
typo in promptwith title directions

### ISSUE THREAD

**Issue by rowej83** [sj82516/vue-alertify#9]
currently is:

 promptWithTitle:function(){
    	this.$alertify.prompt("prompt title""This is prompt", "default value", (evt, value)=>
        	this.$alertify.success("ok: " + value)
        , () => this.$alertify.error("cancel")
        )
    }

It's missing the comma between "prompt title" and "this is prompt", should be:
 promptWithTitle:function(){
    	this.$alertify.prompt("prompt title","This is prompt", "default value", (evt, value)=>
        	this.$alertify.success("ok: " + value)
        , () => this.$alertify.error("cancel")
        )
    }

**Comment by yuanchieh-cheng** [comment]
thanks! 
will update soon

**Comment by sj82516** [comment]
fixed readme
